version: '3.8'
services:
  crud:
    image: crud-image
    build: counter-serv
    depends_on:
      - db
    ports:
      - "${PORT}:${PORT}"
    restart: on-failure
    environment:
      DATABASE_URL: "postgres://username:pgpassword@db:${DB_PORT}/${DB_NAME}"
      DB_HOST: db
      DB_PORT: "${DB_PORT}"
      DB_PASS: "${DB_PASS}"
      DB_LOGIN: "${DB_LOGIN}"
      DB_NAME: "${DB_NAME}"
      PORT: "${PORT}"
    networks:
      - crudNet
  db:
    container_name: db
    image: db
    build: counter-serv/src/DB
    environment:
      POSTGRES_USER: ${DB_LOGIN}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
      # DB volumes template
    volumes:
      ['db-data:/var/lib/postgresql/data/']
    ports:
    - ${DB_PORT}:${DB_PORT}
    restart: always
    networks:
      - crudNet
volumes:
  db-data:
    name: db-data
networks:
  crudNet:
    driver: bridge